version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - observability

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.15.0
    container_name: metricbeat
    user: root
    volumes:
      - ./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    command: metricbeat -e -strict.perms=false
    depends_on:
      - kibana
    networks:
      - observability

  # heartbeat:
  #   image: docker.elastic.co/beats/heartbeat:7.13.0
  #   container_name: heartbeat
  #   volumes:
  #     - ./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
  #   environment:
  #     - setup.kibana.host=kibana:5601
  #   networks:
  #     - observability

  # apm:
  #   image: docker.elastic.co/apm/apm-server-oss:7.13.0
  #   container_name: apm
  #   volumes:
  #     - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   ports:
  #     - "8200:8200"
  #   restart: on-failure
  #   networks:
  #     - observability

networks:
  observability:
    external: true
